Update TW Translation
FooIbar/EhViewer pull request #1081
Opened 2024-04-28 14:41 UTC by NeKoOuO

Fix typos, add translation

2024-04-28 15:25 UTC, FooIbar commented
Do you really call gallery "相簿" in TW?
That does not make sense to me.
It seems "畫廊" is more commonly used.
https://ehwiki.org/wiki/Galleries/Chinese
https://www.ptt.cc/bbs/AC_In/M.1584886579.A.F5A.html

2024-04-28 15:28 UTC, FooIbar commented
@5idereal Since you've done this previously, would you mind taking a look?

2024-04-28 15:49 UTC, revonateB0T commented
`New Compose Reader` is added for developers.
This option will be removed and users are forced to use Compose one after it's completed.

2024-04-28 15:55 UTC, revonateB0T commented
> @5idereal Since you've done this previously, would you mind taking a look?

cc @bluehomewu

2024-04-28 17:37 UTC, NeKoOuO commented
Done

2024-04-28 19:57 UTC, bluehomewu reviewed
The suggested items have been replied line by line. Please make corrections for each item.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="clipboard_gallery_url_snack_message">剪貼簿裡有畫廊連結</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="gallery_list_search_bar_open_gallery">開啟畫廊</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="add_quick_search_tip">畫廊列表的狀態將被儲存為快速搜尋。如果你想儲存搜尋面板的狀態，請先進行搜尋。</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="similar_gallery">類似畫廊</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="clear_image_cache_confirm">為該畫廊清除所有快取圖片？</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +      <string name="no_current_torrents">沒有當前版本畫廊的種子</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="newer_version_available">此畫廊有新版本可以使用。</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="gallery_info">畫廊資訊</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="key_parent">上層畫廊</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="gallery_comments">畫廊留言</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="gallery_previews">畫廊預覽</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="reset_reading_progress_message">重置所有已下載畫廊的閱讀進度？</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="filter">隱藏畫廊</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="filter_tip">該隱藏系統會在 EHentai 網站隱藏系統的基礎上繼續隱藏畫廊。\n\n標題隱藏項：排除標題含有該關鍵字的畫廊。\n\n上傳者隱藏項：排除該上傳者上傳的畫廊。\n\n標籤隱藏項：排除包含該標籤的畫廊，這會使獲取畫廊列表花費更多時間。\n\n標籤組隱藏項：排除包含該標籤組的畫廊，這會使獲取畫廊列表花費更多時間。</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_eh_gallery_site">畫廊站臺</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_eh_show_gallery_pages_summary">在畫廊列表中顯示頁數</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
>      <string name="settings_eh_show_gallery_comments_summary">在畫廊詳情頁中顯示評論</string>
Don't forget.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_eh_filter_summary">根據標題、上傳者、標籤、評論者隱藏畫廊或評論</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_download_media_scan_summary_off">大部分畫廊軟體將會忽略顯示下載路徑中的影像</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="favorite_name">收藏畫廊</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="download_gallery_first">請先下載畫廊！</string>
We use "相簿" or "圖庫" as gallery in Taiwan.

2024-04-28 19:57 UTC, bluehomewu commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="animate_items_summary">如遇崩潰/掉幀請嘗試禁用此項</string>
"停用" is better than "禁用", "禁用" is used in China.

2024-04-29 02:37 UTC, FooIbar commented
Disclaimer: I'm not Taiwanese so just some thoughts.

The "gallery" here is more like a specific term of E-Hentai, not something you would use for gallery apps (e.g. Samsung Gallery).
To distinguish this from other uses, I think it's fine to give it a different translation like "畫廊".
In EhWiki, both "圖庫" and "畫廊" are used, but "相簿" seems not fit here.
![image](https://github.com/FooIbar/EhViewer/assets/118464521/6c34ab71-1057-43b3-a29b-cc89220031ef)

2024-04-29 03:07 UTC, NeKoOuO commented
I also think so

2024-04-29 03:26 UTC, bluehomewu commented
> Disclaimer: I'm not Taiwanese so just some thoughts.
> 
> The "gallery" here is more like a specific term of E-Hentai, not something you would use for gallery apps (e.g. Samsung Gallery). To distinguish this from other uses, I think it's fine to give it a different translation like "畫廊". In EHWiki, both "圖庫" and "畫廊" are used, but "相簿" seems not fit here. ![image](https://private-user-images.githubusercontent.com/118464521/326316970-6c34ab71-1057-43b3-a29b-cc89220031ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjEzMjIsIm5iZiI6MTcxNDM2MTAyMiwicGF0aCI6Ii8xMTg0NjQ1MjEvMzI2MzE2OTcwLTZjMzRhYjcxLTEwNTctNDNiMy1hMjliLWNjODkyMjAwMzFlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwMzIzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjAxMjgwZWIzMDkwYTVkOTJiNWMwNDllMTAyZGRhZTQ2YTY1NmY3NTgxNmM2YTdiNGU5OTRiYzMyZjhkNjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ycK7eeIW17Y81EP8sbvDjM1yvPQoYxrYlPHarsbJc2Y)

We named "Google Photos" as " Google 相簿", "ASUS Gallery" as "ASUS圖片庫".
I still hold my opinion. I think it is "相簿" is more better.

2024-04-29 04:06 UTC, revonateB0T commented
> Disclaimer: I'm not Taiwanese so just some thoughts.
> 
> The "gallery" here is more like a specific term of E-Hentai, not something you would use for gallery apps (e.g. Samsung Gallery). To distinguish this from other uses, I think it's fine to give it a different translation like "畫廊". In EHWiki, both "圖庫" and "畫廊" are used, but "相簿" seems not fit here. ![image](https://private-user-images.githubusercontent.com/118464521/326316970-6c34ab71-1057-43b3-a29b-cc89220031ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjMyMjgsIm5iZiI6MTcxNDM2MjkyOCwicGF0aCI6Ii8xMTg0NjQ1MjEvMzI2MzE2OTcwLTZjMzRhYjcxLTEwNTctNDNiMy1hMjliLWNjODkyMjAwMzFlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwMzU1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2UzNGU3MmJhOTE1ZTI4ZWM3NGUzYzY2MDRkZWQ4N2MyYmE5ODUyZjhmMzA0YjBkNmQ3MDU3Njg3YTVkYWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rU5wIw-aTT2aD3krvhBjtw-tOXVJpJ4s9dhKVZEs1Uk)

Why would you consider `相簿` is not appropriate here?
Do you look down on cosplay?
Just kidding XD.
I personally don't make any comments as I'm not Taiwanese.

2024-04-29 04:10 UTC, NeKoOuO commented
I personally think that the term '相簿' cannot fully convey the original meaning.

Because that thing in EH is not exactly a '相簿' I think it's a bit inappropriate to translate it as '相簿'

2024-04-29 04:31 UTC, FooIbar commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_download_media_scan_summary_off">大部分畫廊軟體將會忽略顯示下載路徑中的影像</string>
This should be "相簿" regardless as it's referring to gallery apps.

2024-04-29 04:50 UTC, FooIbar commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="animate_items">列表專案動畫</string>
"專案" looks suspicious.

2024-04-29 05:19 UTC, 5idereal commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="animate_items">列表專案動畫</string>
Should be "列表項目動畫".

2024-04-29 05:30 UTC, 5idereal commented
Why can't we keep "圖庫" as the translation? I don't think it needs to be changed. As @FooIbar says, "相簿" doesn't fit here, and "畫廊" is the Simplified Chinese term.

2024-04-29 05:42 UTC, NeKoOuO commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_download_media_scan_summary_off">大部分畫廊軟體將會忽略顯示下載路徑中的影像</string>
not sure 337

2024-04-29 06:11 UTC, NeKoOuO commented
> Why can't we keep "圖庫" as the translation? I don't think it needs to be changed. As @FooIbar says, "相簿" doesn't fit here, and "畫廊" is the Simplified Chinese term.

Okay I'll change it later

2024-04-29 09:20 UTC, NeKoOuO commented
Done

2024-04-29 09:26 UTC, FooIbar commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_download_media_scan_summary_off">大部分畫廊軟體將會忽略顯示下載路徑中的影像</string>
337 is also referring to gallery apps if you look at the original text.
```
Please hide your gallery apps away from other people
```

2024-04-29 09:29 UTC, FooIbar commented on app/src/main/res/values-zh-rTW/strings.xml
> +      <string name="no_current_torrents">沒有當前版本圖庫的種子</string>
Redundant spaces.

2024-04-29 09:40 UTC, FooIbar commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="settings_about_declaration_summary">EhViewer 與 E-Hentai.org 無任何聯絡</string>
We want to express `association` rather than `communication` here, is `聯絡` proper?

2024-04-29 09:50 UTC, FooIbar approved these changes
LGTM, but someone else must approve.

2024-04-29 09:55 UTC, revonateB0T approved these changes

2024-04-29 11:32 UTC, 5idereal requested changes
Please revert the changes for line 501 and 481.

2024-05-18 16:05 UTC, NeKoOuO commented
Done

2024-05-18 17:26 UTC, FooIbar commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="archive_resample">重新取樣檔案</string>
These should be as short as possible because the button has limited width, see #1085

2024-05-18 18:40 UTC, NeKoOuO commented
Done

2024-05-19 07:41 UTC, FooIbar commented
Thank you! And thanks to everyone for reviewing!

2024-05-19 07:41 UTC, merged